import type { Metadata } from "next";
import { interFont } from "@/global/font";
import "@radix-ui/themes/styles.css";
import "@/global/globals.scss";
import { Theme } from "@radix-ui/themes";
import {AppHeader} from "@/components/header/header";


export const metadata: Metadata = {
  title: "Match Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans dark base-brand bg-background">
    <head>
      <meta name="color-scheme" content="light dark"/>
      <meta name="theme-color" content="#090909"/>
      <title></title>
    </head>
      <body className={`${interFont.className} antialiased`}>
        <Theme grayColor="slate" className="pb-10.5">
          <AppHeader />
          {children}
        </Theme>
      </body>
    </html>
  );
}
